algoritmo "conteate10"
var

 valor, salto, contador: inteiro
inicio
        contador <- 0
        Escreva("quer contar até quanto?")
        leia (valor)
        Escreval("Qual sera o valor do salto? ")
        leia(salto)
        enquanto (contador <= valor) faca
        Escreval(contador)
                 Contador <- contador + salto
        Fimenquanto
        escreval ("terminei de contar")
fimalgoritmo